---
title: |
  <center> School + State Finance Project </center>
  <center> Data Analyst Skills Exercise </center>
author: "Sarah Brashear"
date: "Last Modified: 4/4/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r packages}
library(tidyverse)
library(readxl)
library(janitor)
```

```{r data_prep}
raw_data <- read_excel("2021-03-29_Data_for_Skills_Exercise.xlsx",
                       sheet = "Data",
                       skip = 1,
                       col_names = TRUE)

clean_data <- raw_data %>%
  clean_names() 
```

```{r explore}
# Exploratory Data Analysis

view(clean_data)
summary(clean_data)

# Since traditional indicators of SES include income, education, and occupation,
# I'm looking at variables related to these first. 
```

```{r explore_income}
# Median Household Income
summary(clean_data$median_household_income)

# Median Household Income ranges from $34,338 to $219,083, indicating wide
# disparity of income between towns. 
# Mean = $91,779; Median = $89,255

# Visualizing the spread of median household income:
income_plot <- clean_data %>%
  ggplot(aes(x = median_household_income)) +
  geom_histogram(aes(y = stat(count)/sum(stat(count))),
                 bins = 70) +
  labs(title = "Distribution of Median Household Income",
       x = "Median Household Income",
       y = "Percent of Connecticut Towns") +
  scale_y_continuous(labels = scales::percent_format()) +
  theme_classic()

quantile(clean_data$median_household_income, probs = c(0.05, 0.95))

# 90% of towns have median household income between $55,421 and $140,375

```

```{r explore_education}
# Education

# This data set includes five discrete bins of educational attainment; it's not 
# reported on a continuous scale.

# I'm creating an educational attainment scale for each town that is continuous.
# Each education bin will be assigned to a multiplier (0-4) with larger values
# corresponding to more advanced educational attainment. 

# Then, I will multiply the number of residents with that degree of educational
# attainment by each multiplier, and divide by the total number of residents
# represented in the educational attainment data. 

# Note: I am not dividing by the population, which may include residents under
# age 25, and therefore may skew the index in towns with particularly large or 
# small numbers of children in the population.

# The purpose of this scale is to represent the fact that higher degrees of 
# educational attainment likely yield higher SES outcomes in the long-run. I 
# also wanted to avoid oversimplifying the available data like I would have if 
# I had simply created a dichotomous variable (like college/no college, for 
# example), and then calculated the percent of each town that has a college 
# degree. 

ed_scale_data <- clean_data %>%
  select(less_than_high_school_diploma, high_school_diploma_ged_or_equivalent, 
         some_college, associates_degree, bachelors_degree_or_higher) %>%
  rowwise() %>% 
    mutate(total = sum(c_across())) %>%
    mutate(ed_scale = ((less_than_high_school_diploma * 0) +
                      (high_school_diploma_ged_or_equivalent * 1) + 
                      (some_college * 2) +
                      (associates_degree * 3) +
                      (bachelors_degree_or_higher * 4)) /
              total)

# Now that the scores are calculated for each municipality, I am adding back in
# the municipality name so I can join by municipality name later on.
ed_scale_data$municipality=c(clean_data$municipality)


summary(ed_scale_data$ed_scale)

# The education index ranges from 1.550 to 3.549
# Mean = 2.509; Median = 2.525

education_plot <- ed_scale_data %>%
  ggplot(aes(x = ed_scale)) +
  geom_histogram(aes(y = stat(count)/sum(stat(count))),
                 bins = 50) +
  labs(title = "Distribution of Educational Attainment",
       x = "Education Index",
       y = "Percent of Connecticut Towns") +
  scale_y_continuous(labels = scales::percent_format()) +
  theme_classic()

quantile(ed_scale_data$ed_scale, probs = c(0.05, 0.95))

# 90% of towns fall between 1.86 and 3.17 on the educational attainment scale.
# Substantively, this isn't particularly insightful since these aren't in 
# meaningful units. 
```

```{r explore_occupation}
# Occupation
# Traditional SES indices tend to consider type of labor (unemployed, unskilled,
# skilled, professional). Since I don't have that data, I'm looking at 
# unemployment rates as a measure of occupation.

summary(clean_data$unemployment_rate)

# Unemployment Rate ranges from 2.4% to 6.9%
# For context, the U.S. unemployment rate in 2018 was 3.86%

# Visualizing the spread of unemployment rate:
home_value_plot <- clean_data %>%
  ggplot(aes(x = unemployment_rate)) +
  geom_histogram(aes(y = stat(count)/sum(stat(count))),
                 bins = 70) +
  labs(title = "Distribution of Unemployment Rates",
       x = "Unemployment Rate",
       y = "Percent of Connecticut Towns") +
  scale_y_continuous(labels = scales::percent_format()) +
  scale_x_continuous(labels = scales::percent_format())
  theme_classic()
  
quantile(clean_data$unemployment_rate, probs = c(0.05, 0.95))

# 90% of towns have unemployment rates between 2.87% and 5.14%.
```


```{r dimension_indices}
# After analyzing the available data, I decided to create an SES index made up
# of the three component parts outlined above: Median Household Income, 
# Educational Attainment, and Employment Rate. 

# The first step was to transform these variables, which are expressed 
# in different units, into indices that fall between 0 and 1. 

# The formula I used is below:

# Dimension Index = (actual value - minimum value) / 
#                   (maximum value - minimum value)

```

```{r income_index}
# The goal posts for a town's median household income are $30,000 for the lower
# limit, and $200,000 for the upper limit. 

income_index_data <- clean_data %>%
  select(municipality, median_household_income) %>%
  mutate(income_index = ((median_household_income - 30000) / 
                           (220000 - 30000))) %>%
  select(municipality, income_index)
```

```{r education_index}
# The goal posts for a town's median educational attainment are 1.5 for the 
# lower limit, and 3.5 for the upper limit. 

education_index_data <- ed_scale_data %>%
  select(municipality, ed_scale) %>%
  mutate(education_index = ((ed_scale - 1.5) / 
                           (3.5 - 1.5))) %>%
  select(municipality, education_index)
```

```{r employment_index}
# For this component, I'm using the percentage employed, rather than unemployed.
# The lower goalpost is 90% and the upper goalpost is 100% employment.

employment_index_data <- clean_data %>%
  select(municipality, unemployment_rate) %>%
  mutate(employment_rate = 1 - unemployment_rate) %>%
  mutate(employment_index = ((employment_rate - .90) / 
                           (1.00 - .90))) %>%
  select(municipality, employment_index)
```

```{r SES_index}
# Now that I have each component of my SES index, I need to aggregate the 
# indices into one total measure value.

# I'm choosing to give equal weight to each component, although an argument could
# be made for assigning more or less weight to each element. 

# Another thing that could alter the weight assigned to each component part is
# choosing different upper and lower goalpost limits in the previous step, when 
# I transformed the variables to scales of 0 to 1. 

SES_index_data <- inner_join(income_index_data, education_index_data, by = "municipality") %>%
  inner_join(employment_index_data, by = "municipality") %>%
  mutate(SES_index = (income_index * education_index * employment_index)^(1/3)) %>%
  select(municipality, SES_index) 

# Ultimately, the SES Index is the geometric mean of the three component 
# indices (income, education, and employment).
```

